// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package data

import "fyne.io/fyne/v2"

var resourceAuthors = &fyne.StaticResource{
	StaticName: "AUTHORS",
	StaticContent: []byte("Andrew Wang <wangyazhoujy@gmail.com>"),
}
